project:
  type: website
  render:
    - "*.md"
    - "*.Rmd"
    - "*.qmd"
    - "*.ipynb"
  output-dir: ../docs

website:
  title: "chemProbing"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Analyses"
        menu:
        - text: "2025.5.7: C12 C15 pilot testing"
          href: 2025.5.7.html
        - text: "2025.5.8: re-analysis of previous data"
          href: 2025.5.8.html
        - text: "2025.5.27-a: Plasmidsaurus data re-analysis (part-1)"
          href: 2025.5.27-a.html
        - text: "2025.5.27-b: Plasmidsaurus data re-analysis (part-2)"
          href: 2025.5.27-b.html
        - text: "2025.5.27-c: Plasmidsaurus data re-analysis (part-3)"
          href: 2025.5.27-c.html
        - text: "2025.5.28-a: Azenta Amplicon-EZ (part-1)"
          href: 2025.5.28-a.html
        - text: "2025.5.28-b: Azenta Amplicon-EZ (part-2)"
          href: 2025.5.28-b.html
        - text: "2025.5.28-c: Azenta Amplicon-EZ (part-3)"
          href: 2025.5.28-c.html
        - text: "2025.5.29-a: Amplicon-seq analysis troubleshooting"
          href: 2025.5.29-a.html
        - text: "2025.5.29-b: Project-1. Small molecule-binding RNA structural probing"
          href: 2025.5.29-b.html
        - text: "2025.5.29-c: Project-2. Activity-based RNA profiling"
          href: 2025.5.29-c.html
        - text: "2025.6.9-a: Project-1 - C12/C15 Temperature gradient from 40째C to 80째C"
          href: 2025.6.9-a.html
        - text: "2025.6.9-b: Project-1 - C34 structural protection at 50째C and 60째C"
          href: 2025.6.9-b.html
      - text: "Misc."
        href: misc.html
    right:
      - text: Source code
        icon: github
        href: https://github.com/chenh19/chemProbing

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex
    include-after-body: _footer.html
