project:
  type: website
  render:
    - "*.md"
    - "*.Rmd"
    - "*.qmd"
    - "*.ipynb"
  output-dir: ../docs

website:
  title: "chemProbing"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Analyses"
        menu:
        - text: "Part-1: html from .Rmd"
          href: part-1.html
      - text: "Misc."
        href: misc.html
    right:
      - text: Source code
        icon: github
        href: https://github.com/chenh19/chemProbing

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex
