project:
  type: website
  render:
    - "*.md"
    - "*.Rmd"
    - "*.qmd"
    - "*.ipynb"
  output-dir: ../docs

website:
  title: "chemProbing"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Analyses"
        menu:
        - text: "2025.5.7: C12 C15 pilot testing"
          href: 2025.5.7.html
        - text: "2025.5.8: re-analysis of previous data"
          href: 2025.5.8.html
        - text: "2025.5.27-a: Plasmidsaurus data re-analysis (part-1)"
          href: 2025.5.27-a.html
        - text: "2025.5.27-b: Plasmidsaurus data re-analysis (part-2)"
          href: 2025.5.27-b.html
        - text: "2025.5.27-c: Plasmidsaurus data re-analysis (part-3)"
          href: 2025.5.27-c.html
      - text: "Misc."
        href: misc.html
    right:
      - text: Source code
        icon: github
        href: https://github.com/chenh19/chemProbing

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex
